[workspace]
members = ["crates/*"]

[workspace.package]
authors = ["Wasmer Engineering Team <engineering@wasmer.io>"]
edition = "2021"
homepage = "https://wasmer.io/"
license = "MIT"
readme = "README.md"
repository = "https://github.com/wasmerio/wasmer-pack"
rust-version = "1.64.0"                                       # Required for [workspace.package]
version = "0.5.0"

[patch.crates-io]
wai-bindgen-gen-core = { git = "https://github.com/wasmerio/wai", branch = "commonjs" }
wai-bindgen-gen-js = { git = "https://github.com/wasmerio/wai", branch = "commonjs" }
wai-bindgen-gen-wasmer-py = { git = "https://github.com/wasmerio/wai", branch = "commonjs" }
wai-parser = { git = "https://github.com/wasmerio/wai", branch = "commonjs" }
