[workspace]
members = ["crates/*"]

[workspace.package]
authors = ["Wasmer Engineering Team <engineering@wasmer.io>"]
edition = "2021"
homepage = "https://wasmer.io/"
license = "MIT"
readme = "README.md"
repository = "https://github.com/wasmerio/wit-pack"
rust-version = "1.64.0"                                       # Required for [workspace.package]
version = "0.4.1"
