[workspace]
members = ["crates/*"]

[patch."https://github.com/wasmerio/wit-bindgen"]
# Note We are using a temporary fork until the following PRs are merged
# and end up in the wasmerio/wit-bindgen repo's "wasmer" branch.
#
# https://github.com/bytecodealliance/wit-bindgen/pull/304
# https://github.com/wasmerio/wit-bindgen/pull/7
wit-bindgen-gen-core = { git = "https://github.com/Michael-F-Bryan/wit-bindgen", branch = "wasmer-temp" }
wit-bindgen-gen-wasmer-py = { git = "https://github.com/Michael-F-Bryan/wit-bindgen", branch = "wasmer-temp" }
wit-parser = { git = "https://github.com/Michael-F-Bryan/wit-bindgen", branch = "wasmer-temp" }
