[package]
name = "wit-pack-cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.59.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.wapm]
namespace = "Michael-F-Bryan"
abi = "wasi"

[[bin]]
name = "wit-pack"
path = "src/main.rs"
doc = false

[dependencies]
anyhow = "1.0.62"
clap = { version = "3.2.17", features = ["derive"] }
wit-pack = { version = "0.1.0", path = "../wit-pack" }
