[package]
name = "wit-pack-cli"
version = "0.3.0-beta"
edition = "2021"
rust-version = "1.59.0"
description = "A code generator that lets you treat WebAssembly modules like native dependencies."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "wit-pack"
doc = false

[package.metadata.wapm]
namespace = "wasmer"
abi = "wasi"

[dependencies]
anyhow = "1.0.62"
clap = { version = "3.2.17", features = ["derive"] }
webc = { git = "ssh://git@github.com/wasmerio/pirita.git", version = "0.1.0" }
wit-pack = { version = "0.3.0-alpha", path = "../wit-pack" }
