[package]
name = "wit-pack-cli"
version = "0.1.4"
edition = "2021"
rust-version = "1.59.0"
description = "A code generator that lets you treat WebAssembly modules like native dependencies."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.wapm]
namespace = "Michael-F-Bryan"
abi = "wasi"

[[bin]]
name = "wit-pack"
path = "src/main.rs"
doc = false

# Due to issues with SSH, the URL has to be in HTTPS format
[dependencies.pirita]
git = "https://github.com/wasmerio/pirita.git"
version = "0.1.0"
default-features = false
features = ["mmap"]

[dependencies]
anyhow = "1.0.62"
clap = { version = "3.2.17", features = ["derive"] }
wit-pack = { version = "0.1.0", path = "../wit-pack" }
