[package]
name = "wit-pack"
version = "0.1.0"
authors = ["Wasmer Engineering Team <engineering@wasmer.io>"]
repository = "https://github.com/wasmerio/wit-pack"
edition = "2021"
license = "MIT"
rust-version = "1.58.0" # allows things like format!("{variable}")

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
wit-parser = { git = "https://github.com/wasmerio/wit-bindgen", rev = "1750cd0", version = "0.1.0" }
wit-bindgen-gen-js = { git = "https://github.com/wasmerio/wit-bindgen", rev = "1750cd0", version = "0.1.0" }
wit-bindgen-gen-core = { git = "https://github.com/wasmerio/wit-bindgen", rev = "1750cd0", version = "0.1.0" }
serde_json = "1.0.83"
serde = "1.0.143"

[dev-dependencies]
cargo_metadata = "0.15.0"
