[package]
name = "wasmer-pack-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.3.0"
tracing = "0.1.37"
wasmer-pack-cli = { version = "0.5.3", path = "../cli" }
