name: Releases

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  publish-to-wapm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Give GitHub Actions access to wasmerio/pirita
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PIRITA_REPO_DEPLOY_KEY }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.59.0" # Required by wit-bindgen-gen-rust
      - name: Install WebAssembly targets
        run: rustup target add wasm32-unknown-unknown wasm32-wasi
      - name: Install the Wasmer Runtime
        run: curl https://get.wasmer.io -sSfL | sh
      - name: Install cargo-wapm
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-wapm --verbose --debug
      - name: Publish to wapm.dev
        run: |
          wapm config set registry.url https://registry.wapm.dev
          cargo wapm --workspace
      - name: Publish to wapm.io
        run: |
          wapm config set registry.url https://registry.wapm.io
          cargo wapm --workspace
